package sistema.empleadosGUI;

import sistema.empleadosDAL.conexion;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sistema.empleadosBL.empleadosBL;

public class frmEmpleados extends javax.swing.JFrame {
    DefaultTableModel modelo;
    
    /**
     * Creates new form frmEmpleados
     */
    public frmEmpleados() {
        initComponents();
        
        String[] titulos = {"ID","Nombre","Correo"};
        modelo = new DefaultTableModel(null,titulos);
        tblempleados.setModel(modelo);
        
        this.mostrarDatos();
        this.limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblempleados = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblempleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblempleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblempleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblempleados);

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/recursos/agregar.png"))); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/recursos/editar.png"))); // NOI18N
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/recursos/borrar.png"))); // NOI18N
        btnborrar.setText("Borrar");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/recursos/cancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        txtid.setEditable(false);

        jLabel1.setText("ID :");

        jLabel2.setText("Nombre :");

        jLabel3.setText("Correo :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnombre)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnagregar)
                        .addGap(32, 32, 32)
                        .addComponent(btneditar)
                        .addGap(27, 27, 27)
                        .addComponent(btnborrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar)
                    .addComponent(btneditar)
                    .addComponent(btnborrar)
                    .addComponent(btncancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        conexion objConexion = new conexion(); //Conectarse a la BD
        empleadosBL oEmpleados = recuperarDatosGUI(); //Recuperar datos de la interfaz gráfica
        String strSentenciaInsert = String.format("INSERT INTO Empleados(ID,Nombre,Correo) VALUES (null,'%s','%s')",oEmpleados.getNombre(),oEmpleados.getCorreo());
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_btnagregarActionPerformed

    private void tblempleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblempleadosMouseClicked
        if(evt.getClickCount() == 1){
            JTable receptor = (JTable)evt.getSource();
            txtid.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtnombre.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            txtcorreo.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
        }
        btnagregar.setEnabled(false);
        btneditar.setEnabled(true);
        btnborrar.setEnabled(true);
    }//GEN-LAST:event_tblempleadosMouseClicked

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        conexion objConexion = new conexion();
        empleadosBL oEmpleados = recuperarDatosGUI();
        String strSentenciaInsert = String.format("DELETE FROM Empleados WHERE ID = %d",oEmpleados.getID());
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        conexion objConexion = new conexion();
        empleadosBL oEmpleados = recuperarDatosGUI();
        String strSentenciaInsert = String.format("UPDATE Empleados SET Nombre = '%s',Correo = '%s' WHERE ID = %d",oEmpleados.getNombre(),oEmpleados.getCorreo(),oEmpleados.getID());
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_btncancelarActionPerformed
    
    public void mostrarDatos(){  //Para consultar y llenar la tabla
        while(modelo.getRowCount() > 0){  //Para que automáticamente se deje de ver el registro borrado de la tabla en la interfaz
            modelo.removeRow(0);
        }
        
        conexion objConexion = new conexion();
        
        try {
            ResultSet resultado = objConexion.consultarRegistros("SELECT * FROM Empleados");
            while(resultado.next()){
                System.out.println(resultado.getString("ID"));
                System.out.println(resultado.getString("Nombre"));
                System.out.println(resultado.getString("Correo"));
                Object[] oUsuario = {resultado.getString("ID"),resultado.getString("Nombre"),resultado.getString("Correo")};
                modelo.addRow(oUsuario);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public empleadosBL recuperarDatosGUI(){  //Recuperar informaciòn de la interfaz gráfica
        empleadosBL oEmpleados = new empleadosBL();
        
        int ID = (txtid.getText().isEmpty())?0: Integer.parseInt(txtid.getText());
        oEmpleados.setID(ID);
        oEmpleados.setNombre(txtnombre.getText());
        oEmpleados.setCorreo(txtcorreo.getText());
        
        return oEmpleados;
    }
    
    public void limpiar(){
        txtid.setText("");
        txtnombre.setText("");
        txtcorreo.setText("");
        
        btnagregar.setEnabled(true);
        btneditar.setEnabled(false);
        btnborrar.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblempleados;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
